basePath: /
definitions:
  schema.ChangePasswordRequest:
    properties:
      current_password:
        type: string
      email:
        type: string
      new_password:
        type: string
    type: object
  schema.DeleteAccountRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  schema.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  schema.GenericResponse:
    properties:
      message:
        type: string
    type: object
  schema.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  schema.LoginResponse:
    properties:
      token:
        type: string
    type: object
  schema.SignupRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  schema.SignupResponse:
    properties:
      data:
        properties:
          token:
            type: string
        type: object
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API for DBHose
  title: DBHose API
  version: "1.0"
paths:
  /change-password:
    post:
      consumes:
      - application/json
      description: Change the password for a user account
      parameters:
      - description: Password change request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Change user password
      tags:
      - Authentication
  /delete:
    post:
      consumes:
      - application/json
      description: Permanently delete a user account and associated data
      parameters:
      - description: Account deletion request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.DeleteAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete a user account
      tags:
      - Authentication
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a session token
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: Log in a user
      tags:
      - Authentication
  /logout:
    post:
      description: Invalidate the user's session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Log out a user
      tags:
      - Authentication
  /signup:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Signup Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.SignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.SignupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: Sign up a new user
      tags:
      - Authentication
swagger: "2.0"
