basePath: /
definitions:
  domain.Credential:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      secret:
        additionalProperties:
          type: string
        type: object
      updated_at:
        type: string
    type: object
  domain.Log:
    properties:
      description:
        type: string
      duration:
        description: 1h2m3s
        type: string
      email:
        type: string
      file:
        type: string
      name:
        type: string
      timestamp:
        description: "2006-01-02 15:04:05"
        type: string
    type: object
  schema.ChangePasswordRequest:
    properties:
      current_password:
        type: string
      email:
        type: string
      new_password:
        type: string
    type: object
  schema.CredentialsResponse:
    properties:
      credentials:
        items:
          $ref: '#/definitions/domain.Credential'
        type: array
    type: object
  schema.DeleteAccountRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  schema.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  schema.GenericResponse:
    properties:
      message:
        type: string
    type: object
  schema.LogResponse:
    properties:
      data:
        additionalProperties:
          items:
            $ref: '#/definitions/domain.Log'
          type: array
        type: object
      message:
        type: string
    type: object
  schema.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  schema.LoginResponse:
    properties:
      token:
        type: string
    type: object
  schema.SignupRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  schema.SignupResponse:
    properties:
      data:
        properties:
          token:
            type: string
        type: object
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API for DBHose
  title: DBHose API
  version: "1.0"
paths:
  /backup/{key}:
    post:
      consumes:
      - application/json
      description: Backup a database
      parameters:
      - description: Credential key
        in: path
        name: key
        required: true
        type: string
      - description: request
        in: query
        name: secret
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: Backup a database
      tags:
      - Migration
  /change-password:
    post:
      consumes:
      - application/json
      description: Change the password for a user account
      parameters:
      - description: Password change request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: Change user password
      tags:
      - Authentication
  /credential:
    get:
      consumes:
      - application/json
      description: List stored credentials
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.CredentialsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: List credentials
      tags:
      - Credential
    post:
      consumes:
      - application/json
      description: Backup DB credentials
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: Store credentials
      tags:
      - Credential
    put:
      consumes:
      - application/json
      description: Edit stored credentials
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: Edit credentials
      tags:
      - Credential
  /credential/{id}:
    delete:
      consumes:
      - application/json
      description: Delete stored credentials
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: Delete credentials
      tags:
      - Credential
    get:
      consumes:
      - application/json
      description: View stored credentials
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.CredentialsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: View credentials
      tags:
      - Credential
  /delete:
    post:
      consumes:
      - application/json
      description: Permanently delete a user account and associated data
      parameters:
      - description: Account deletion request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.DeleteAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: Delete a user account
      tags:
      - Authentication
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a session token
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: Log in a user
      tags:
      - Authentication
  /logout:
    post:
      description: Invalidate the user's session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: Log out a user
      tags:
      - Authentication
  /logs:
    get:
      consumes:
      - application/json
      description: Fetch logs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.LogResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: Fetch logs
      tags:
      - Migration
  /restore/{key}:
    post:
      consumes:
      - application/json
      description: Restore a database
      parameters:
      - description: Credential key
        in: path
        name: key
        required: true
        type: string
      - description: request
        in: query
        name: secret
        required: true
        type: string
      - description: Backup file
        in: query
        name: file
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      security:
      - Bearer: []
      summary: Restore a database
      tags:
      - Migration
  /signup:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Signup Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schema.SignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.SignupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: Sign up a new user
      tags:
      - Authentication
swagger: "2.0"
